#NumPy

In [2]:
import numpy as np

#ndim

In [ ]:
##arrayimizin boyutunu belirleyebiliriz bu yöntemle.
arr = np.array([1, 2, 3, 4], ndmin = 5)
print(arr)
print(arr.ndim) #arrayin kaç boyutlu olduğunu gösteren metod
print(type(arr)) #numpy veri tipi

#Data Type 

In [ ]:
"""
i - integer
b - boolean
u - unsigned integer
f - float
c - complex float
m - timedelta
M - datetime
O - object
S - string
U - unicode string
V - fixed chunk of memory for other type ( void )
"""

In [ ]:
#dtype= metoduyla arrayimizin veri tipini değiştirebiliriz.
arr2 = np.array([1, 2, 3, 4], dtype="S")
print(arr2)
print(arr2.dtype)

In [ ]:
arr3 = np.array([1, 2, 3, 4], dtype="i4") #integer olduğunu gösteren i'nin yanına sayılar yazarak kaç byte istediğimizi yazabiliriz
print(arr3)
print(arr3.dtype)

In [ ]:
newarr = arr2.astype("f") # varolan bir arrayi kopyalayıp veri tipini depğiştirme
print(newarr)
print(newarr.dtype)

# Copy ve View

In [ ]:
arr4 = np.array([1, 2, 3, 4, 5])
x = arr4.copy() ##copy metodunda değişikliler bir anlam ifade etmez ve orijinal array korunur.
arr4[0] = 0
print(arr4)
print(x)
#
y = arr4.view() #view metodunda eğer orijinal array değişikliğe uğramışsa view edilen arrayde de değişiklik olur.
arr4[0] = 26
print(arr4)
print(y)
#base metoduyla view mi copy mi olduğunu anlarız. eğer base metodunda None ifadesi varsa copy; bir array datası varsa view'dir

print(x.base)
print(y.base)

# Shape 


In [ ]:
print(arr.shape)
print(arr4.shape)

# Reshape

In [ ]:
#unknown dimension = eğer bir arrayda kaç eleman olduğunu bilmiyorsa reshape sonundaki sayıyı "-1" yaparsan numpy senin yerine otomatik olarak hesaplar.
arr5 = np.array([1, 2, 3, 4, 5, 6, 7, 8])
newarr = arr5.reshape(2, 2, -1)
print(newarr)
#reshape(-1) metoduyla çok boyutlu bir arrayi tek boyutlu hale getirebiliriz.
print(arr5.reshape(-1))

#iterating

In [ ]:
#iteratind 1-d array
arr = np.array([1, 2, 3, 4, 5])
for i in arr:
  print(i)

In [ ]:
#iterating 2-d array
arr2d = np.array([[1, 2, 3, 4], [4, 5, 6, 7]])
for i in arr2d:
  print(i)
#
for i in arr2d:
  for j in i:
    print(j)


In [ ]:
# iterating 3-d array
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
for i in arr3d:
  print("i represents the 2-D array:")
  print(i)
for i in arr3d:
  for j in i:
    for k in j:
      print(k)

In [ ]:
#nditer() metodu = çok boyutlu arrayleri fazla döngü kullanmadan döndürmemize yarar 
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
for i in np.nditer(arr3d):
  print(i)
for i in np.nditer(arr):
  print(i)


In [ ]:
#Başka veri tipleri ile iterate etme 
#op_dtypes argümanı sayesinde veri tipi değiştirilebilir.
#fakat NumPy arraylerdeki elemanları değiştirmeye izin vermez. Bunun için de flags=['buffered'] argümanı kullanırız.

arr = np.array([1, 2, 3])
for i in np.nditer(arr, flags = ["buffered"], op_dtypes=["float64"]):
  print(i)

In [ ]:
##enumerate iteration
#.ndenumerate
#arraylerin indexlenmesi de diyebiliriz.
arr = np.array([1, 2, 3])
for i in np.ndenumerate(arr):
  print(i)
# 2-d
print("######################2 boyutlu arraylerin enumerate edilmesi ###########################")
arr2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
for i in np.ndenumerate(arr2d):
  print(i)


#Numpy arraylerini join etme


In [ ]:
#concatenate() fonksiyonuyla yapılır.

In [19]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))
print(arr)


[1 2 3 4 5 6]


In [21]:
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1) ##2 boyutlu arraylarda axis=1 olursa sütunlar birleşir
print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [16]:
#Stack fonksiyonuyla arraleri birleştirme
  #concatenate() fonksiyonuna benzerdir. Tek farkı arraylere yeni boyutu gibi gösterir.
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2))
print(arr)

[[1 2 3]
 [4 5 6]]


In [23]:
# satır boyunca stack fonksiyonu = hstack() = (horizontal) = concatenate((a,b), axis=1)
arr1 = np.array([[1, 2, 3],[4, 5, 6]])

arr2 = np.array([[7, 8, 9], [10, 11, 12]])

arr = np.hstack((arr1, arr2))

print(arr)


[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [15]:
#sütun boyunca stack fonksiyonu = vstack()= concatenate((a,b), axis=0)
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.vstack((arr1, arr2))

print(arr)

[[1 2 3]
 [4 5 6]]


In [ ]:
#uzunluk(derinlik) boyunca stack fonksiyonu = dstack() = depth
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.dstack((arr1, arr2))

print(arr)

# NumPy Splitting Array

In [24]:
#join metodunun tersidir.
#arraylari bölmek için "array_split()" fonksiyonu kullanılır.

In [27]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

newarr = np.array_split(arr,3)
print(newarr)
print(newarr[0]) #array elementi gibi yeni arraylere böyle erişebiliriz.
print(newarr[1])
print(newarr[2])

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]
[1 2 3]
[4 5 6]
[7 8 9]


In [30]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9]) #illa hepsi aynı sayıda olmak zorunda değil.Eğer split() fonksiyonunu kullanmak istersek eşit bölmekzorundayız yoksa hata alırız.
np.array_split(arr,4)

[array([1, 2, 3]), array([4, 5]), array([6, 7]), array([8, 9])]

#Splitting 2-D Arrays

In [31]:
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

newarr = np.array_split(arr, 3)

print(newarr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [32]:
#hsplit() = hstack() fonksiyonunun tersidir. aynı zamanda array_split(arr,3,axis=1) ile de oluşturulabilir.
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.hsplit(arr, 3)

print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [ ]:
#Similar alternates to vstack() and dstack() are available as vsplit() and dsplit().

#Searching Arrays

In [33]:
#where() metodu kullanılır.
#bir arrayda aradığımız kesin bir değer varsa where() metoduyla o değerin hangi indexlerde olduğunu öğreniriz.
arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x)

(array([3, 5, 6]),)


In [36]:
#çift sayıları bulma
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 0)

print(x)
#tek sayıları bulma
y = np.where(arr%2 == 1)
print(y)

(array([1, 3, 5, 7]),)
(array([0, 2, 4, 6]),)


In [4]:
#Search Sorted
#searchsorted()
#parantezin içine önce hangi arrayde yapacağımızı yazarız, daha sonra gireceğimiz değeriyazarız. Gireceğimiz değerin/değerlerin hangi indexte olması gerektiğini gösterir.
#bu metod aramaya soldan başlar.
arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7.5)

print(x)

2


In [6]:
#eğer sağdan başlamasını istiyorsak aşağıdaki metodu uygularız.
#searchsorted(array,değer,side="right") metoduyla sağdan başlanır.
arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7.5, side='right')

print(x)

2


In [7]:
## çoklu değerlerle searchsorted() çalışmak

arr = np.array([1, 3, 5, 7])
x = np.searchsorted(arr, [2, 4, 6])
print(x)

[1 2 3]


#Sorting Arrays

In [10]:
#sorted()
#bu metod orijinal arrayi bozmaz, orijinal arrayi kopyalar ve sıralar.
# nümerik veya alfabetik ; aşağıdan yukarıya veya yukarıdan aşağıya sıralama yapılabilir.
arr = np.array([3, 2, 0, 1])

print(np.sort(arr))

arr1 = np.array(["banana", "apple", "cherry"])
print(np.sort(arr1))

[0 1 2 3]
['apple' 'banana' 'cherry']


In [11]:
#Sorting a 2-D Array
arr = np.array([[3, 1, 7], [9, 2, 0]])
print(np.sort(arr))

[[1 3 7]
 [0 2 9]]


In [12]:
#Filtering Arrays
arr = np.array([41, 42, 43, 44])

x = [True, False, True, False]

newarr = arr[x]

print(newarr)
#True olanları yeni arraye ekler sadece.

[41 43]


In [17]:
#örnek 2:
arr = np.array([41, 42, 43, 44])
filtering_arr = []
for i in arr:
  if i > 42:
    filtering_arr.append(True)
  else:

    filtering_arr.append(False)

new_arr = arr[filtering_arr]
print(filtering_arr)
print(new_arr)
print("#############################################")
#veya daha kısa yol olarak:
arr = np.array([41, 42, 43, 44])
filter_arr = arr > 42
new_arr2 = arr[filtering_arr]
print(filter_arr)
print(new_arr2)

[False, False, True, True]
[43 44]
#############################################
[False False  True  True]
[43 44]


In [18]:
#örnek 3:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
filtering_arr = []
for i in arr:
  if i%2 == 0 :
    filtering_arr.append(True)
  else:
    filtering_arr.append(False)
new_arr = arr[filtering_arr]
print(filtering_arr)
print(new_arr)
print("#############################################")
#veya daha kısa yol olarak :
arr = np.array([1, 2, 3, 4, 5, 6, 7])
filter_arr = arr % 2 == 0
new_arr2 = arr[filter_arr]
print(filter_arr)
print(new_arr2)

[False, True, False, True, False, True, False]
[2 4 6]
#############################################
[False  True False  True False  True False]
[2 4 6]
